'use strict';
// Suggested follow-up chips shown under each response (Cursor-style).
//
// These are derived from what the turn actually did (captured in the result
// metadata) rather than generated by a model: that keeps them instant, free,
// and always available — no OPENROUTER_API_KEY or extra paid round-trip per
// turn. The set is intentionally small and high-signal; clicking a chip sends
// its `prompt` to the agent.

/**
 * @param {{ mode?: string, filesEdited?: number, hadError?: boolean }} [meta]
 * @returns {{ label: string, prompt: string }[]} at most three follow-ups
 */
function suggestFollowups(meta) {
	const m = meta || {};
	const filesEdited = typeof m.filesEdited === 'number' ? m.filesEdited : 0;
	const out = [];

	// Plan mode proposes work without doing it — the obvious next step is to run
	// it (as a normal agent turn, i.e. no /plan command on the followup).
	if (m.mode === 'plan') {
		out.push({ label: 'Implement this plan', prompt: 'Implement the plan you just described.' });
		out.push({ label: 'Refine the plan', prompt: 'Refine the plan: call out risks, edge cases, and the exact files you will touch.' });
		return out;
	}

	if (m.hadError) {
		out.push({ label: 'Try a different approach', prompt: "That didn't work. Try a different approach and explain why it should fix the issue." });
	}

	if (filesEdited > 0) {
		out.push({ label: 'Review the changes for bugs', prompt: 'Review the changes you just made for bugs, edge cases, and regressions.' });
		out.push({ label: 'Add or update tests', prompt: 'Add or update tests covering the changes you just made, then run them.' });
	} else if (!m.hadError) {
		out.push({ label: 'Make these changes', prompt: 'Go ahead and implement what you just described.' });
		out.push({ label: 'Go deeper', prompt: 'Explain this in more depth, with concrete examples from the code.' });
	}

	return out.slice(0, 3);
}

module.exports = { suggestFollowups };
